import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Second blog',
  description: 'Generated by create next app'
}

export default function SecondBlog () {
  return (
    <div>
      <h1>Second Blog</h1>
      <Link href='/' className='link'>
        Back to home
      </Link>
    </div>
  )
}
